### PR TITLE
config: export manage_network_ns_lifecycle

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by giuseppe** [comment]
added a patch that helps to test with `manage_network_ns_lifecycle = true`

**Comment by giuseppe** [comment]
I've been looking at adding a new tests to aos-cd-jobs but I am struggling on how we can refactor it to avoid duplicating completely an existing file.  What I want is a copy of `./sjb/config/test_cases/test_pull_request_crio_e2e_fedora.yml` where the difference is in the way the script is called:

```
    script: |-
      ansible-playbook -vv --become  \
                       -i localhost, \
                       --tags e2e    \
                       -e manage_network_ns_lifecycle=True \
                       --become-user root \
                       --connection local \
                       /go/src/github.com/kubernetes-sigs/cri-o/contrib/test/integration/main.yml
```

the difference being the extra `manage_network_ns_lifecycle` setting.

What is the preferred way to achieve it in Ansible?

@stevekuznetsov

**Comment by mrunalp** [comment]
@giuseppe https://github.com/openshift/release/

**Comment by mrunalp** [comment]
nvm you know where the script are at :)

**Comment by giuseppe** [comment]
> nvm you know where the script are at :)

my knowledge might not be updated :-)  last time I've worked on it, it was in aos-cd-jobs.  Is it still the case?

**Comment by stevekuznetsov** [comment]
Yeah you guys are one of the last teams still using the legacy Jenkins approach from aos-cd-jobs

**Comment by stevekuznetsov** [comment]
I think you can override evars like here:

https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald.yml#L11

and pass this var to ansible like so https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald.yml#L61

**Comment by giuseppe** [comment]
> I think you can override evars like here:
> 
> https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald.yml#L11
> 
> and pass this var to ansible like so https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_pull_request_origin_aggregated_logging_journald.yml#L61

Thanks!  I've opened a WIP PR here: https://github.com/openshift/aos-cd-jobs/pull/1766

**Comment by umohnani8** [comment]
LGTM

**Pull request merged**
