### PR TITLE
Badges and revert

### PR DESCRIPTION
**Pull request by runcom**
**- What I did**

added fancy badges to the readme and revert useless commits

**- How I did it**

vi

**- How to verify it**

check it out

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
Looks like the cause is https://github.com/kubernetes/kubernetes/pull/69441 which has caused other test issues in general, let's see

**Comment by mrunalp** [comment]
Yeah that is failing for us consistently. We can open a revert if no one does tomorrow.

**Comment by runcom** [comment]
@mrunalp this is ready

**Pull request merged**
