### PR TITLE
server: Spawn goroutine for updating exited container status

### PR DESCRIPTION
**Pull request by mrunalp**
I am working on patches to stop container. This is the first of them.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

**- What I did**
Made exit container update code concurrent.

**- How I did it**
Added goroutine for updating exited container status.

**- How to verify it**
Tests pass

### CODE REVIEW

**Comment by rhatdan** [comment]
Not sure why, but LGTM

**Comment by umohnani8** [comment]
@mrunalp needs rebase

**Comment by mrunalp** [comment]
Closing this since Giuseppe fixed what we wanted to do already.

**Pull request closed without merging**
