### PR TITLE
[DO NOT MERGE] release 1.12

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

just syncing up with kube 1.12

**- How I did it**

vim & vndr

**- How to verify it**

check it out!

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
do not merge nor lgtm nor nothing, still working on this

**Comment by pixdrift** [comment]
Is there a schedule/ETA for the 1.12 release? Sorry, wasn't sure where best to ask.

**Comment by mrunalp** [comment]
@pixdrift We will try to have it out by the end of the week.

**Comment by runcom** [comment]
This PR is still around cause we still need fixes from #1822 once that lands to release 1.12 (#1822 is for master)

**Comment by AkihiroSuda** [comment]
Does CRI-O v1.12 supports Kubernetes v1.12 `securityContext.procMount` ?

Corresponding commit for containerd is https://github.com/containerd/cri/pull/894 , but could not find similar commit in this repo.

**Comment by runcom** [comment]
@AkihiroSuda that's in https://github.com/kubernetes-sigs/cri-o/pull/1820/commits/ff2c3e1909ec3d1526509bba0a5dd92fc1c9c417

**Pull request closed without merging**
