### PR TITLE
WIP - Storage rw lock

### PR DESCRIPTION
**Pull request by vrothberg**
**- What I did**

Vendor the latest containers/image and vrothberg/storage to test if the reader-writer locks from https://github.com/containers/storage/pull/278 cause any regressions.

**- How to verify it**

Running the CI :)

This is work in progress. Please do not merge.

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan @runcom @mrunalp can you drop an "/ok-to-test" to let me play with the CI?

**Comment by mrunalp** [comment]
crio.service is failing due to -
```
-- Logs begin at Mon 2019-02-04 12:40:02 UTC, end at Mon 2019-02-04 12:44:46 UTC. --
Feb 04 12:44:29 ip-172-18-16-114.ec2.internal systemd[1]: Starting Open Container Initiative Daemon...
Feb 04 12:44:29 ip-172-18-16-114.ec2.internal crio[26706]: time="2019-02-04 12:44:29.294599584Z" level=fatal msg="overlay: Unknown option overlay.override_kernel_check"
Feb 04 12:44:29 ip-172-18-16-114.ec2.internal systemd[1]: crio.service: main process exited, code=exited, status=1/FAILURE
Feb 04 12:44:29 ip-172-18-16-114.ec2.internal systemd[1]: Failed to start Open Container Initiative Daemon.
Feb 04 12:44:29 ip-172-18-16-114.ec2.internal systemd[1]: Unit crio.service entered failed state.
Feb 04 12:44:29 ip-172-18-16-114.ec2.internal systemd[1]: crio.service failed.
```

**Comment by mrunalp** [comment]
Did containers/storage remove that option recently?

**Comment by nalind** [comment]
Yes, it did.  It had been unnecessary for some time.

**Comment by mrunalp** [comment]
@vrothberg You can remove the overlay option as part of this PR and the tests shouldn't fail on that anymore.

**Comment by vrothberg** [comment]
> This is a bug in containers/storage. We should just print a debug message if a user uses this option, it should not fail.

That's happening for btrfs since I know the tools. Shall all drivers (not just overlay) throw a deprecation debug message?

**Comment by vrothberg** [comment]
@mrunalp I think the bot is running wild. It's flooding with failed-test messages.

**Comment by vrothberg** [comment]
I restarted the test to stop the bot from spamming.

**Comment by mrunalp** [comment]
Can we close this temporarily?

**Comment by mrunalp** [comment]
Can we close this temporarily?

**Comment by mrunalp** [comment]
Closing to prevent bot spam.

**Comment by vrothberg** [comment]
I'll open a new PR to continue poking CI. The bot must have had a bad day.

**Pull request closed without merging**
