### PR TITLE
conmon: Adjust OOM score to low value

### PR DESCRIPTION
**Pull request by mrunalp**
We don't want conmon to be killed.

@giuseppe @rhatdan @umohnani8 ptal.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@giuseppe Do we want to skip this setting oom_score_adj for rootless and/or podman?

**Comment by rhatdan** [comment]
I would figure this will break if you run it as a non privileged user.

**Comment by rhatdan** [comment]
I would figure this requires CAP_RESOURCE to be allowed.

**Comment by umohnani8** [comment]
LGTM

**Comment by giuseppe** [comment]
We could probably just ignore errors or print a warning. It shouldn't be a fatal error if we fail to set this value

**Comment by mrunalp** [comment]
Updated to not fail on errors.

**Comment by haircommander** [comment]
LGTM

**Comment by haircommander** [comment]
Update: this is totally fatal if we are not root, and we may need to get a new version of conmon into libpod. @mrunalp @giuseppe any advise on a fix? I get 
```
failed to write to /proc/self/oom_score_adj: Permission denied
``` for everything i do as rootless

**Comment by giuseppe** [comment]
Does that also stop common?  I will take a look

**Comment by haircommander** [comment]
oh nevermind,  it is just a warning

**Comment by haircommander** [comment]
though, the error message is concerning from a podman perspective. It may be worth ignoring the error all together, unless maybe a user says to force adjust oom score or something?

**Pull request merged**
