### PR TITLE
Add saschagrunert as owner

### PR DESCRIPTION
**Pull request by saschagrunert**
As discussed via mail with @mrunalp it would be a pleasure to me to serve as maintainer for cri-o. :pray:

I'm not sure if there is anything else needed than just modifying the OWNERS file. Let me know if I can do anything in particular. :innocent:

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by vrothberg** [comment]
LGTM :+1:

**Comment by saschagrunert** [comment]
Thanks guys!

**Comment by mrunalp** [comment]
@saschagrunert You will need to follow up with a PR like this - https://github.com/kubernetes/org/pull/560/files.

**Comment by mrunalp** [comment]
Also, if you aren't a kubernetes-sigs member, then first open a PR like this - https://github.com/kubernetes/org/issues/550.

**Comment by saschagrunert** [comment]
> @saschagrunert You will need to follow up with a PR like this - https://github.com/kubernetes/org/pull/560/files.

Ah thanks for noticing it. So I would need two sponsors to confirm the request.
I'm kindly asking, If you, @giuseppe @mrunalp @rhatdan @runcom @sboeuf @umohnani8 would like to be my sponsor?

**Comment by saschagrunert** [comment]
> @saschagrunert I will sponsor you.
> What do I need to do?

Thank you very much, I would need your `LGTM` at https://github.com/kubernetes/org/issues/641

**Pull request merged**
