### PR TITLE
v1.13.x: vendor latest containers/image for parallel pulling

### PR DESCRIPTION
**Pull request by vrothberg**
In combination with the recent usage of the pgzip library, pulling an
image is up to 2 times faster.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

Backport of #1964

Cc: @mrunalp

### CODE REVIEW

**Comment by vrothberg** [comment]
@mrunalp @rhatdan given kata is flaky, I think this PR is ready for merge.

**Comment by mrunalp** [comment]
lgtm

**Pull request merged**
