### PR TITLE
update github.com/containers/* dependencies

### PR DESCRIPTION
**Pull request by vrothberg**
This implies some changes to the code to adapt to some API changes, and
to change some transitive dependencies that are added or dropped.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Fixes: #2196

**Comment by saschagrunert** [comment]
@vrothberg Thanks for taking care of this one! :+1: I think we will run into some test problems here, which I already tried to fix partly in #2191. I will stop there and give this one precedence. Feel free to reach me out if you need any support... :upside_down_face:

**Comment by vrothberg** [comment]
> @vrothberg Thanks for taking care of this one!  I think we will run into some test problems here, which I already tried to fix partly in #2191. I will stop there and give this one precedence. Feel free to reach me out if you need any support...

Thanks! I'll apply the changes to the unit tests as well :+1:

**Comment by saschagrunert** [comment]
LGTM

**Comment by saschagrunert** [comment]
LGTM

**Comment by mrunalp** [comment]
Rebasing to master should fix the tests.

**Comment by vrothberg** [comment]
@saschagrunert @giuseppe @rhatdan can you drop a LGTM?

**Comment by saschagrunert** [comment]
@vrothberg Do we want to backport this to the 1.14 release branch?

**Comment by vrothberg** [comment]
> @vrothberg Do we want to backport this to the 1.14 release branch?

May God have mercy on us :) I think we should backport that to be on the safe side. There is a bunch of fixes in the updated dependencies that we should use.

**Pull request merged**
