### PR TITLE
Use current status for list calls

### PR DESCRIPTION
**Pull request by mrunalp**
cc: @runcom

### CODE REVIEW

**Comment by giuseppe** [comment]
should we just drop the Lock from `ContainerStatus`?  AFAICS, `ContainerStatus` takes a lock but then it returns the pointer to the `ContainerState`  and it is unlocked when used by the caller of `ContainerStatus`.  Or do we need to change `ContainerStatus` to return a copy instead?

**Comment by mrunalp** [comment]
@giuseppe :+1: I think we should make ContainerStatus return a copy.

**Comment by runcom** [comment]
@giuseppe would you address your comment in another PR maybe?

**Pull request merged**
