### PR TITLE
Pause credentials 1.12

### PR DESCRIPTION
**Pull request by mtrmac**
See https://github.com/kubernetes-sigs/cri-o/pull/2115 for the `master` version of this PR.

**- What I did**

Added support for supplying credentials necessary for pulling the pause image.

**- How I did it**

Added a `pause_image_auth_file` config option, and a corresponding `--pause-image-auth-file` CLI option.

They are disabled by default, preserving the current behavior. Users have to opt in by explicitly pointing at a config file.

**- How to verify it**

Ultimately, run with `--pause-image-auth-file` in the CLI, or the `pause_image_auth_file` option (I didn’t do that yet.)

The `master` version of this PR has GoMock-based tests; this branch does not use GoMock, so this PR does not add them.

**- Description for the changelog**

New config and CLI options allow supplying credentials necessary for pulling the pause image.

### CODE REVIEW

**Comment by mrunalp** [comment]
I was able to test this locally using a local docker registry with authentication :+1:

**Comment by mrunalp** [comment]
The changes LGTM but I would like if @runcom or @vrothberg can give this a look as well before we merge.

**Comment by vrothberg** [comment]
Commit e3a6f17311b05e17718750d9d0c901f9a41a2571 might not be needed for a backport but besides that LGTM. As always, a pleasure to read @mtrmac's PRs with easy to digest commits :+1:

**Comment by mtrmac** [comment]
(

> Commit [e3a6f17](https://github.com/kubernetes-sigs/cri-o/commit/e3a6f17311b05e17718750d9d0c901f9a41a2571) might not be needed for a backport but besides that LGTM.

For the record, that commit is ~necessary so that the newly added code does not have to worry about priority of the new config option vs. pre-existing configuration, and so that we don’t add non-obviously dead code.)

**Pull request merged**
