### PR TITLE
docs: fix links to policy.json, registries.conf

### PR DESCRIPTION
**Pull request by jpoon**
**- What I did**

Fixed broken links in docs.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

docs: fix links to policy.json, registries.conf

### CODE REVIEW

**Comment by mrunalp** [comment]
@jpoon You need to sign the commit. Thanks!

**Comment by rhatdan** [comment]
LGTM

**Comment by jpoon** [comment]
screen shot 2018-11-02 at 1 13 29 pm

GH gives me that green `verified`. Is there another sort of signing I'm missing?  @mrunalp

**Comment by mrunalp** [comment]
travis is failing whitespace validation for commit message:
```
IT_CHECK_EXCLUDE="./vendor" /home/travis/gopath/bin/git-validation -q -run DCO,short-subject,dangling-whitespace
 02d65cb - FAIL - has whitespace errors. See `git show --check 02d65cb21c58ecfb3c260360cacd0307dbf05a73`.
1 commits to fix
```

**Pull request merged**
