### PR TITLE
bump github.com/containers/storage and github.com/containers/image

### PR DESCRIPTION
**Pull request by nalind**
Bump github.com/containers/storage and github.com/containers/image, to commits 06b6c2e4cf254f5922a79da058c94ac2a65bb92f and 93bced01015eb94bec4821df1876314be8197680, respectively.  This is intended to fix manifest mismatches that produce `Manifest does not match provided manifest digest` errors.

### CODE REVIEW

**Comment by mtrmac** [comment]
@nalind This needs also https://github.com/kubernetes-sigs/cri-o/pull/2064/commits/6d385029d99da638ec0ed99382b16e1f69595f8b (the second commit of https://github.com/kubernetes-sigs/cri-o/pull/2064 )

**Comment by nalind** [comment]
> @nalind This needs also [6d38502](https://github.com/kubernetes-sigs/cri-o/commit/6d385029d99da638ec0ed99382b16e1f69595f8b) (the second commit of #2064 )

Ah, thanks!  Grabbing it.

**Comment by mrunalp** [comment]
I think we should port this to 1.13 as well as we intend to move 1.13 soon.

**Comment by nalind** [comment]
> I think we should port this to 1.13 as well as we intend to move 1.13 soon.

Opened #2071.

**Pull request merged**
