### PR TITLE
runPodSandbox: clean up containers on error path

### PR DESCRIPTION
**Pull request by mythi**
If the CNI setup fails in runPodSandbox, the infra container started is
not stopped/removed and leaks.

Ensure the necessary clean-up steps are executed on error
path.

Fixes: #1816

### CODE REVIEW

**Comment by mrunalp** [comment]
@mythi Do you mind opening a PR to release-1.11 branch as well? Thanks!

**Comment by mythi** [comment]
@mrunalp PR #1818 created. I just manually moved the changes to ```server/sandbox_run.go```

**Pull request merged**
