### PR TITLE
update containers/{image,storage}

### PR DESCRIPTION
**Pull request by vrothberg**
The changes to containers/image entail additional changes to the
dependencies since the progress-bar libraries have been changed.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@mrunalp PTAL. Once that's merged, I will start with the vendor cleanup, and adding `make vendor` checks to the CI to make sure everything's in sync.

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by vrothberg** [comment]
CI really doesn't like me. There's another (green) PR including the containers/storage updates, so I am closing this one and open a separate update for containers/image.

**Pull request closed without merging**
