### PR TITLE
vendor latest containers/image for parallel pulling

### PR DESCRIPTION
**Pull request by vrothberg**
In combination with recent usage of the pgzip library, pulling an image
is up to 2 times faster.                                               
                                                                       
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
argh, the tests are failing because we didn't upgrade containers/storage and containers/image for long time.

Could you rebase on top of my PR since I've already fixed these?

**Comment by vrothberg** [comment]
> argh, the tests are failing because we didn't upgrade containers/storage and containers/image for long time.
> 
> Could you rebase on top of my PR since I've already fixed these?

sure :)

**Comment by vrothberg** [comment]
Brilliant, tests are passing \o/

**Comment by rhatdan** [comment]
Ship it.  :^)

**Comment by vrothberg** [comment]
Reminder to prepare PRs for 1.12 and 1.13 once this one is merged.

**Comment by mrunalp** [comment]
I think we can merge this as the kata issue is something else that we are hitting on all PRs.

**Comment by mrunalp** [comment]
Now we need backports to `release-1.12` and `release-1.13` :)

**Pull request merged**
