### PR TITLE
[release 1.11] Vendor latest containers/storage and containers/image

### PR DESCRIPTION
**Pull request by umohnani8**
Brings in storage lock fixes.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@mrunalp @runcom PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by nalind** [comment]
LGTM

**Comment by mrunalp** [comment]
integration tests failed.

**Comment by mrunalp** [comment]
This needs to be looked at in the test VMs. The issues must definitely be related to the changes we are bringing in this PR. The other PRs aren't hitting any issues in integration.

**Comment by mrunalp** [comment]
@umohnani8 @nalind We use vfs storage driver in travis and overlay in integration_rhel and integration_fedora which might explain why travis isn't failing.

**Comment by nalind** [comment]
I'm reasonably certain that this is a combination of the bug that https://github.com/containers/storage/pull/214 fixed interacting with https://github.com/containers/storage/pull/210 to make things even more confusing.

**Comment by umohnani8** [comment]
With the containers/storage commit being vendored in for this PR, Shutdown() doesn't unmount the storage driver's root as it thinks a rootfs is still mounted since the lock wasn't being managed correctly when importing the cached images from .artifacts.
Using containers/storage master and containers/image#505 fixes this issue. Will wait till containers/image#505 gets in so we can vendor in the changes here.

**Comment by umohnani8** [comment]
Looks like the e2e_rhel tests are timing out. The logs don't have a summary of tests and stop halfway through one of the tests.

**Comment by runcom** [comment]
should we kick e2e_rhel again (at least one more time)?

**Comment by umohnani8** [comment]
It passed this time. @runcom you want to run it one more time?

**Pull request merged**
