### PR TITLE
test: Increase number of inotify user watches

### PR DESCRIPTION
**Pull request by mrunalp**
Our tests fail without increasing this limit.

@giuseppe ptal

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
thanks, LGTM

I am worried now if we are leaking inotify watchers fds, either in CRI-O or related to the new patch for the Kubelet.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by giuseppe** [comment]
> I am worried now if we are leaking inotify watchers fds, either in CRI-O or related to the new patch for the Kubelet.

FYI: I am testing inotify leaks but cannot see anything wrong

**Pull request merged**
