### PR TITLE
Fix typos issues

### PR DESCRIPTION
**Pull request by mooncak**
**- What I did**
Fix typos issues in below files:

1. cmd/crio/config.go
2. oci/container.go
3. server/sandbox_remove.go
4. server/sandbox_stop_linux.go

**- How I did it**
Remove the duplications in files.

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.
Thanks for the PR @mooncak !

**Comment by mrunalp** [comment]
The commit needs to be signed. 

`git commit --amend -s` should add it. Thanks!

**Comment by mooncak** [comment]
> The commit needs to be signed.
> 
> `git commit --amend -s` should add it. Thanks!

@mrunalp  Hi, already signed

**Pull request merged**
