### PR TITLE
contrib: test: run e2e in parallel

### PR DESCRIPTION
**Pull request by runcom**
we don't run any serial test so it's ok to move to parallel to speed up
test time. You can check no serial in
https://openshift-gce-devel.appspot.com/build/origin-federated-results/pr-logs/pull/kubernetes-incubator_cri-o/1715/test_pull_request_crio_e2e_fedora/1171/

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
so:
```
Sep  4 13:48:47.279: INFO: At 2018-09-04 13:43:48 +0000 UTC - event for image-pull-test8bedbb56-b048-11e8-aef0-0ee5ec2156b0: {kubelet 127.0.0.1} Failed: Failed to pull image "gcr.io/authenticated-image-pulling/alpine:3.1": rpc error: code = Unknown desc = Invalid image name "", expected colon-separated transport:reference
```
this looks like a bug somewhere similar to #1768

**Comment by runcom** [comment]
do not merge, investigating 2 failures

**Comment by runcom** [comment]
```
Kubernetes e2e suite.[sig-apps] CronJob should remove from active list jobs that have been deleted
```
this is flacking :confused: I'll take a look at it tomorrow.

**Comment by runcom** [comment]
ctr status in memory created time has been picked in #1790

**Comment by runcom** [comment]
Looks promising, I'll pick other needed commits so we can merge them all and finally unblock master

**Comment by runcom** [comment]
All green, restarting e2e just to battle test it

**Comment by mrunalp** [comment]
We got rename changes under vendor which are unintentional and should be removed.

**Comment by runcom** [comment]
> We got rename changes under vendor which are unintentional and should be removed.

they come from the original PR, see https://github.com/kubernetes-sigs/cri-o/pull/1783#discussion_r217459725 - the commit here is reverting the changes

**Comment by runcom** [comment]
wtf
/test e2e_rhel

**Pull request merged**
