### PR TITLE
Add disk usage for ListContainerStats

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Qi Wang <qiwan@redhat.com>

included a patch from Mrunal Patel
PR#1869#issuecomment-459530581

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

See https://github.com/kubernetes-sigs/cri-o/pull/1869 and https://github.com/kubernetes-sigs/cri-o/pull/1869#issuecomment-459530581 . I basically just cherry-picked the original patch and applied mrunal's changes to release-1.12 branch

@mrunalp @vrothberg @rhatdan PTAL

### CODE REVIEW

**Comment by lsm5** [comment]
@QiWang19 PTAL ^

**Comment by lsm5** [comment]
> @lsm5 LGTM, and I think this is porting to release-1.12 so I don't need to do this for 1.12 (from #1869)?

yup, this takes care of it.

**Comment by lsm5** [comment]
@runcom might be just a nit, but does the commit message need to include "cherry-picked from blahblah commit"?

**Comment by runcom** [comment]
Nope, it's fine that's not a pattern we've been using.

**Comment by QiWang19** [comment]
> > @lsm5 LGTM, and I think this is porting to release-1.12 so I don't need to do this for 1.12 (from #1869)?
> 
> yup, this takes care of it.
Do I need to create this PR to release-1.13?

**Comment by lsm5** [comment]
> Do I need to create this PR to release-1.13?

Yup, that'd be great, thanks. Let me know if there's any trouble with it.

**Pull request merged**
