### PR TITLE
pause: remove pause binary from repo

### PR DESCRIPTION
**Pull request by cyphar**
This code was added back when cri-o didn't have the ability to pull
images, and the purpose of 1313f0dd720f ("*: add pause binary as a build
target") was to make it easier to play with cri-o without Docker.

However, cri-o has long-since grown support for image pulling and the
code that used to use the pre-compiled 'pause' binary now uses the
'pause' image. Keeping this binary around doesn't make sense anymore,
especially since it was originally just a copy of the upstream
Kubernetes one.

Signed-off-by: Aleksa Sarai <asarai@suse.de>

**- Description for the changelog**
```
Removed the included pause binary as cri-o uses pause images, and has for a long time.
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Will this work in an environment where there is no access to a public container registry?

**Comment by cyphar** [comment]
> Will this work in an environment where there is no access to a public container registry?

The binary is currently unused by `cri-o` (c0333b102bcbdb367f31924ffa3f4437709dcd38 completely removed all of the code referencing the pause binary), so having it makes no change to the container registry problem. The `pause_image` option should be what most people use to allow them to access private registries (or even just local storage in the case of CaaSP) and use a different pause image.

**Comment by mrunalp** [comment]
No objections from me if we fix up the tests to pass. Thanks!

**Comment by runcom** [comment]
:+1:

**Comment by rhatdan** [comment]
@cyphar Are you still working on this?

**Comment by rhatdan** [comment]
Do we even use the pause executable any longer?

**Comment by wking** [comment]
> Do we even use the pause executable any longer?

We still have [the consumer][0] I'd pointed out [above][1].

[0]: https://github.com/kubernetes-incubator/cri-o/blob/9665f8cc0ee70d0acf6b3ac9f11911aa332874d7/test/helpers.bash#L227
[1]: https://github.com/kubernetes-incubator/cri-o/pull/1521#issuecomment-380863733

**Comment by umohnani8** [comment]
@cyphar needs rebase please.

**Comment by mrunalp** [comment]
Closing this for now.

**Pull request closed without merging**
