### PR TITLE
Update vendor of containers/storage,image,libpod

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
travis' complaining Dan

**Comment by egernst** [comment]
@rhatdan - we've been having some stability issues at the end of last week.  @chavafg - heads up.

**Comment by chavafg** [comment]
I see these errors in the log:

```
# time="2018-07-23 13:51:46.982086432Z" level=error msg="devmapper: Error unmounting device 42d3b36db4b83542b904da0a08cd3abb8903f1cde4b7cbec770dda5963ac8e52: invalid argument" 
# time="2018-07-23 13:51:46.982099214Z" level=debug msg="failed to delete container "0dd2d2a25f3dd876e2654ae0236b252ca36a7b2119ebdfa4657450b25e8f0781": invalid argument" 
# time="2018-07-23T13:51:46Z" level=fatal msg="removing the pod sandbox "9f6d2a1aaad565af84db5a8cb4ca6b9d5a519626aef039cdbb5623808195a7a9" failed: rpc error: code = Unknown desc = failed to delete container k8s_container1_podsandbox1_redhat.test.crio_redhat-test-crio_1 in pod sandbox 9f6d2a1aaad565af84db5a8cb4ca6b9d5a519626aef039cdbb5623808195a7a9: invalid argument" 
# time="2018-07-23 13:51:46.995883679Z" level=debug msg="ListContainersRequest &ListContainersRequest{Filter:&ContainerFilter{Id:,State:&ContainerStateValue{State:CONTAINER_RUNNING,},PodSandboxId:,LabelSelector:map[string]string{},},}" 
# time="2018-07-23 13:51:46.995904019Z" level=debug msg="no filters were applied, returning full container list" 
# time="2018-07-23 13:51:46.995916120Z" level=debug msg="ListContainersResponse: &ListContainersResponse{Containers:[],}" 
# time="2018-07-23 13:51:47.003434725Z" level=debug msg="ListPodSandboxRequest &ListPodSandboxRequest{Filter:&PodSandboxFilter{Id:,State:nil,LabelSelector:map[string]string{},},}" 
# time="2018-07-23 13:51:47.003476245Z" level=debug msg="ListPodSandboxResponse &ListPodSandboxResponse{Items:[&PodSandbox{Id:9f6d2a1aaad565af84db5a8cb4ca6b9d5a519626aef039cdbb5623808195a7a9,Metadata:&PodSandboxMetadata{Name:podsandbox1,Uid:redhat-test-crio,Namespace:redhat.test.crio,Attempt:1,},State:SANDBOX_NOTREADY,CreatedAt:1532353900343687127,Labels:map[string]string{group: test,io.kubernetes.container.name: POD,},Annotations:map[string]string{owner: hmeng,security.alpha.kubernetes.io/seccomp/pod: unconfined,},}],}" 
# time="2018-07-23 13:51:47.010192364Z" level=debug msg="StopPodSandboxRequest &StopPodSandboxRequest{PodSandboxId:9f6d2a1aaad565af84db5a8cb4ca6b9d5a519626aef039cdbb5623808195a7a9,}" 
# time="2018-07-23 13:51:47.010229116Z" level=debug msg="StopPodSandboxResponse 9f6d2a1aaad565af84db5a8cb4ca6b9d5a519626aef039cdbb5623808195a7a9: &StopPodSandboxResponse{}" 
# Stopped sandbox 9f6d2a1aaad565af84db5a8cb4ca6b9d5a519626aef039cdbb5623808195a7a9
# time="2018-07-23 13:51:47.017528326Z" level=debug msg="RemovePodSandboxRequest &RemovePodSandboxRequest{PodSandboxId:9f6d2a1aaad565af84db5a8cb4ca6b9d5a519626aef039cdbb5623808195a7a9,}" 
# time="2018-07-23T13:51:47Z" level=fatal msg="removing the pod sandbox "9f6d2a1aaad565af84db5a8cb4ca6b9d5a519626aef039cdbb5623808195a7a9" failed: rpc error: code = Unknown desc = failed to delete container k8s_container1_podsandbox1_redhat.test.crio_redhat-test-crio_1 in pod sandbox 9f6d2a1aaad565af84db5a8cb4ca6b9d5a519626aef039cdbb5623808195a7a9: `/usr/local/bin/kata-runtime delete --force 0dd2d2a25f3dd876e2654ae0236b252ca36a7b2119ebdfa4657450b25e8f0781` failed: Container ID (0dd2d2a25f3dd876e2654ae0236b252ca36a7b2119ebdfa4657450b25e8f0781) does not exist
#   (exit status 1)" 
```

there are some `invalid argument` which makes me think something changed that maybe it is not supported in kata? 

In the kata-runtime log, I see some delete pod errors: 
```
Jul 22 10:19:02 ubuntu-1604-174 kata-runtime[4350]: time="2018-07-22T10:19:02.737689171Z" level=info arguments="\"delete --force 5f277145f78506ec7e95d1bb5731bf035be77e15d058fdce71f6916aad808976\"" command=delete commit=14d25b82a4a73e98
bf9591ce960c946e91c60f53 name=kata-runtime pid=4350 source=runtime version=1.1.0
Jul 22 10:19:02 ubuntu-1604-174 kata-runtime[4350]: time="2018-07-22T10:19:02.741474337Z" level=info msg="path mounted" command=delete container=5f277145f78506ec7e95d1bb5731bf035be77e15d058fdce71f6916aad808976 name=kata-runtime path=/s
ys/fs/cgroup/memory pid=4350 sandbox=68227d13bf88cc10e675e7590dfeb35722dc7fd7dfadf94f17117d831003addf source=runtime type=cgroup
Jul 22 10:19:02 ubuntu-1604-174 kata-runtime[4350]: time="2018-07-22T10:19:02.741558583Z" level=info msg="path mounted" command=delete container=5f277145f78506ec7e95d1bb5731bf035be77e15d058fdce71f6916aad808976 name=kata-runtime path=/s
ys/fs/cgroup/cpu pid=4350 sandbox=68227d13bf88cc10e675e7590dfeb35722dc7fd7dfadf94f17117d831003addf source=runtime type=cgroup
Jul 22 10:19:02 ubuntu-1604-174 kata-runtime[4350]: time="2018-07-22T10:19:02.741590241Z" level=info msg="path mounted" command=delete container=5f277145f78506ec7e95d1bb5731bf035be77e15d058fdce71f6916aad808976 name=kata-runtime path=/s
ys/fs/cgroup/pids pid=4350 sandbox=68227d13bf88cc10e675e7590dfeb35722dc7fd7dfadf94f17117d831003addf source=runtime type=cgroup
Jul 22 10:19:02 ubuntu-1604-174 kata-runtime[4410]: time="2018-07-22T10:19:02.860660444Z" level=info msg="loaded configuration" command=delete file=/usr/share/defaults/kata-containers/configuration.toml format=TOML name=kata-runtime pid=4410 source=runtime
Jul 22 10:19:02 ubuntu-1604-174 kata-runtime[4410]: time="2018-07-22T10:19:02.860818741Z" level=info arguments="\"delete --force 5f277145f78506ec7e95d1bb5731bf035be77e15d058fdce71f6916aad808976\"" command=delete commit=14d25b82a4a73e98bf9591ce960c946e91c60f53 name=kata-runtime pid=4410 source=runtime version=1.1.0
Jul 22 10:19:02 ubuntu-1604-174 kata-runtime[4410]: time="2018-07-22T10:19:02.860881891Z" level=error msg="Container ID (5f277145f78506ec7e95d1bb5731bf035be77e15d058fdce71f6916aad808976) does not exist" command=delete name=kata-runtime pid=4410 source=runtime
```

cc @sboeuf , @egernst

**Comment by chavafg** [comment]
@rhatdan do you know if we need to update the devicemapper version or add a new flag? because we saw that the first error message comes from devicemapper, when trying to umount a device:
```
# time="2018-07-23 13:51:46.982086432Z" level=error msg="devmapper: Error unmounting device 42d3b36db4b83542b904da0a08cd3abb8903f1cde4b7cbec770dda5963ac8e52: invalid argument" 
```

I could also reproduce the failure using runc.

**Comment by rhatdan** [comment]
In the umount man page it says
       EINVAL target is not a mount point.

**Comment by rhatdan** [comment]
Not much has changed in the devicemapper path

git diff dd88b2de829b1af21724a55a96a8e1b2acf8e739 vendor/github.com/containers/storage/drivers/devmapper/
diff --git a/vendor/github.com/containers/storage/drivers/devmapper/deviceset.go b/vendor/github.com/containers/storage/drivers/devmapper/deviceset.go
index 0fab980b..cbf67b3e 100644
--- a/vendor/github.com/containers/storage/drivers/devmapper/deviceset.go
+++ b/vendor/github.com/containers/storage/drivers/devmapper/deviceset.go
@@ -2690,7 +2690,7 @@ func NewDeviceSet(root string, doInit bool, options []string, uidMaps, gidMaps [
                        devices.filesystem = val
                case "dm.mkfsarg":
                        devices.mkfsArgs = append(devices.mkfsArgs, val)
-               case "dm.mountopt":
+               case "dm.mountopt", "devicemapper.mountopt":
                        devices.mountOptions = joinMountOptions(devices.mountOptions, val)
                case "dm.metadatadev":
                        devices.metadataDevice = val

**Comment by rhatdan** [comment]
@nalind @rhvgoyal Any ideas?

**Comment by rhatdan** [comment]
Seems Kata is still not happy with this patch.  @rhvgoyal any ideas?

**Comment by chavafg** [comment]
Hi @rhatdan, I was trying to look at where does the failures come from, so I wanted to run the tests in the `containers/storage` repository using devicemapper driver.
I ran them using https://github.com/containers/storage/blob/master/hack/run_ci_tests.sh. I could run them using vfs and overlay but I couldn't make them work using devicemapper driver, these were the issues I found:

I changed the driver on the `helpers.bash`:
```
-STORAGE_DRIVER=${STORAGE_DRIVER:-vfs}
-STORAGE_OPTION=${STORAGE_OPTION:-}
+STORAGE_DRIVER=${STORAGE_DRIVER:-devicemapper}
+STORAGE_OPTION=${STORAGE_OPTION:-dm.directlvm_device=/dev/sdb}
```

But I got this error:
```
# time="2018-08-02T21:58:02Z" level=debug msg="Root: /tmp/tmp.ieuyzm9c5388k73z/root"
# time="2018-08-02T21:58:02Z" level=debug msg="Run Root: /tmp/tmp.ieuyzm9c5388k73z/runroot"
# time="2018-08-02T21:58:02Z" level=debug msg="Driver Name: devicemapper"
# time="2018-08-02T21:58:02Z" level=debug msg="Driver Options: [dm.directlvm_device=/dev/sdb]"
# time="2018-08-02T21:58:02Z" level=debug msg="[graphdriver] trying provided driver "devicemapper""
# time="2018-08-02T21:58:02Z" level=debug msg="devicemapper: kernel dm driver version is 4.37.0"
# time="2018-08-02T21:58:02Z" level=debug msg="Setting up direct lvm mode" direct-lvm-config={/dev/sdb 0 0 0 0} storage-driver=devicemapper
# error initializing: /dev/sdb is already part of a volume group "storage": must remove this device from any volume group or provide a different device
```

Then tried to use the option `dm.directlvm_device_force=true`:

```
-STORAGE_DRIVER=${STORAGE_DRIVER:-vfs}
-STORAGE_OPTION=${STORAGE_OPTION:-}
+STORAGE_DRIVER=${STORAGE_DRIVER:-devicemapper}
+STORAGE_OPTION=${STORAGE_OPTION:-dm.directlvm_device=/dev/sdb, dm.directlvm_device_force=true}
```

But seems like I am not specifying the option as it is needed, as I got this error:
```
# time="2018-08-02T21:27:05Z" level=debug msg="Root: /tmp/tmp.uxxhaoyxnsedzvfg/root"
# time="2018-08-02T21:27:05Z" level=debug msg="Run Root: /tmp/tmp.uxxhaoyxnsedzvfg/runroot"
# time="2018-08-02T21:27:05Z" level=debug msg="Driver Name: devicemapper"
# time="2018-08-02T21:27:05Z" level=debug msg="Driver Options: [dm.directlvm_device=/dev/sdb, dm.directlvm_device_force=true]"
# time="2018-08-02T21:27:05Z" level=debug msg="[graphdriver] trying provided driver "devicemapper""
# time="2018-08-02T21:27:05Z" level=debug msg="devicemapper: kernel dm driver version is 4.37.0"
# time="2018-08-02T21:27:05Z" level=debug msg="Setting up direct lvm mode" direct-lvm-config={/dev/sdb, dm.directlvm_device_force=true 0 0 0 0} storage-driver=devicemapper
# error initializing: /dev/sdb, dm.directlvm_device_force=true is not available for use with devicemapper
```

Do you know how can I specify more than one storage option to overcome this error?
Or is another way of running the tests for using devicemapper?

**Comment by rhatdan** [comment]
Does /etc/containers/storage.conf have mount-opt defined?

**Comment by rhvgoyal** [comment]
One of the error message says /dev/sdb is busy and not free. Can you provide output of following commands to see who is using /dev/sdb.

'''
- lsblk
- lvs
- pvs
- vgs
'''

**Comment by chavafg** [comment]
@rhatdan I actually do not have `/etc/containers/storage.conf` do we need it? because I think the tests are run inside a container using docker.

@rhvgoyal , this is the output: 
```
fuentess@kata-xenial:~/go/src/github.com/containers/storage$ sudo lsblk
NAME                                                                                    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop1                                                                                     7:1    0  200M  0 loop
└─container-0:58-214-pool                                                               253:0    0  300M  0 dm
  ├─container-0:58-214-6a160a950cd2fbef7c336916b008696d833bc4acfd429f2341132cc3f947fef1 253:1    0  300M  0 dm
  ├─container-0:58-214-89cce4db621e4c1b9d1fa41cbf884f4fbc07cea02e5130ab327fe437941393d7 253:30   0  300M  0 dm
  ├─container-0:58-214-07b0ac290d048da7519372c13b682d728a5759262c94994bb5706bfd4d828731 253:20   0  300M  0 dm
  ├─container-0:58-214-42d1e930244e21262d150a7a36b8ff480d1271f8288f6b9b2978311e91e36375 253:10   0  300M  0 dm
  ├─container-0:58-214-a0b7f232c0848482d585627297697832706412481d02e4e5a115a1b34cb59f26 253:29   0  300M  0 dm
  ├─container-0:58-214-e5ea7e4c946071a2cc5b7b09525311bbfc5f1c0f88670e7fd4fc63e2da754b42 253:19   0  300M  0 dm
  ├─container-0:58-214-eff5d731c12fac1f707ecfe2e5a0312bb0d50a8a7bc594411421e088d0f95492 253:8    0  300M  0 dm
  ├─container-0:58-214-b8da5cae9e4b21628f33603f57223a9d2f71ea35c921a2e8f8a482a124872a1f 253:27   0  300M  0 dm
  ├─container-0:58-214-2e6d6e214e35e1fd462b443263d8682389664c8ac79f25f375f7378383a8d633 253:17   0  300M  0 dm
  ├─container-0:58-214-a59798dba6e28a47c73d6f7f3c72e6789ed61ef92573c7681d75455d07438a0c 253:6    0  300M  0 dm
  ├─container-0:58-214-bd8b249589b94d89be207def266ebde4322bb537af711f4f6c2647caf43575b5 253:25   0  300M  0 dm
  ├─container-0:58-214-f4ab2fa56afcbe1d2b9471629d39379726ec85d9dc413aae6a6378d87cddb6c5 253:15   0  300M  0 dm
  ├─container-0:58-214-a7b59a6452dec7875146a2a116537b34939740222be11bcbfea5e439c2bb9b2e 253:4    0  300M  0 dm
  ├─container-0:58-214-ecd6a44cfcb073271a605b28dab3eaf2467dce9f9bdf1f432e4fc577fa050a3f 253:23   0  300M  0 dm
  ├─container-0:58-214-a8e8ad2a31a552da9da274b2ee49f956a6918eed49534cf6c9d31a4db33ad218 253:13   0  300M  0 dm
  ├─container-0:58-214-9270e22487cc39faf1cbc3abf75f3074e91aaf545d22c59e5131b664ba8d7395 253:2    0  300M  0 dm
  ├─container-0:58-214-033f3541104a57efc52e81465e0d09044b2b207f7d1b97f9b8284183aece27fb 253:11   0  300M  0 dm
  ├─container-0:58-214-d45e9c752a0568fd7b2466a6561993816da5fb856eafc7c3f9701b99e3f7f291 253:9    0  300M  0 dm
  ├─container-0:58-214-360e2aec1431b2014c4881aebb946180f87e458a210fc4662f9366638b7263bf 253:28   0  300M  0 dm
  ├─container-0:58-214-ea00d067934b45645ea4dfa432b5114809fbf0b346497de2c5b869ff18ed4127 253:18   0  300M  0 dm
  ├─container-0:58-214-4812ce92662814c34c378df3f92b7607c8922b7614807883117bb13d38fc0eeb 253:7    0  300M  0 dm
  ├─container-0:58-214-abe135da71aec96d1553fe7e6ad598e8f9eefd9a5de8ecfc834f04615beb6a9d 253:26   0  300M  0 dm
  ├─container-0:58-214-7fecee9c62f05b300a765be27bdaed7466b544286f38a7d25630d37406ada419 253:16   0  300M  0 dm
  ├─container-0:58-214-bc7ded9e60a19b89fe34f1cf2c4da36757c9e0ca265ef10e4a2a5aa896bd1568 253:5    0  300M  0 dm
  ├─container-0:58-214-955104feaf86370bdd924d5a543dd3a8c417301018631896e1a36114dd44b85a 253:24   0  300M  0 dm
  ├─container-0:58-214-4f4b854955c5fa094c2b720b9cf48e3dbcc6626d8a93fc9ed60b5d712957a814 253:14   0  300M  0 dm
  ├─container-0:58-214-ac37c6f0174afdd813592227cecd33bd905fa0152307c441385d719a23bedb60 253:3    0  300M  0 dm
  ├─container-0:58-214-30f0d1ed75b809d65ed616d89f9b6bb9fe8c72e9e9ac7be4cad6f30ab7c85882 253:22   0  300M  0 dm
  └─container-0:58-214-9328cb707ef2b1bab9167d77964c2f8385f4c38b1eac0c7d71a735048b9dec81 253:12   0  300M  0 dm
sdb                                                                                       8:16   0   32G  0 disk
sr0                                                                                      11:0    1 1024M  0 rom
loop0                                                                                     7:0    0  300M  0 loop
└─container-0:58-214-pool                                                               253:0    0  300M  0 dm
  ├─container-0:58-214-6a160a950cd2fbef7c336916b008696d833bc4acfd429f2341132cc3f947fef1 253:1    0  300M  0 dm
  ├─container-0:58-214-89cce4db621e4c1b9d1fa41cbf884f4fbc07cea02e5130ab327fe437941393d7 253:30   0  300M  0 dm
  ├─container-0:58-214-07b0ac290d048da7519372c13b682d728a5759262c94994bb5706bfd4d828731 253:20   0  300M  0 dm
  ├─container-0:58-214-42d1e930244e21262d150a7a36b8ff480d1271f8288f6b9b2978311e91e36375 253:10   0  300M  0 dm
  ├─container-0:58-214-a0b7f232c0848482d585627297697832706412481d02e4e5a115a1b34cb59f26 253:29   0  300M  0 dm
  ├─container-0:58-214-e5ea7e4c946071a2cc5b7b09525311bbfc5f1c0f88670e7fd4fc63e2da754b42 253:19   0  300M  0 dm
  ├─container-0:58-214-eff5d731c12fac1f707ecfe2e5a0312bb0d50a8a7bc594411421e088d0f95492 253:8    0  300M  0 dm
  ├─container-0:58-214-b8da5cae9e4b21628f33603f57223a9d2f71ea35c921a2e8f8a482a124872a1f 253:27   0  300M  0 dm
  ├─container-0:58-214-2e6d6e214e35e1fd462b443263d8682389664c8ac79f25f375f7378383a8d633 253:17   0  300M  0 dm
  ├─container-0:58-214-a59798dba6e28a47c73d6f7f3c72e6789ed61ef92573c7681d75455d07438a0c 253:6    0  300M  0 dm
  ├─container-0:58-214-bd8b249589b94d89be207def266ebde4322bb537af711f4f6c2647caf43575b5 253:25   0  300M  0 dm
  ├─container-0:58-214-f4ab2fa56afcbe1d2b9471629d39379726ec85d9dc413aae6a6378d87cddb6c5 253:15   0  300M  0 dm
  ├─container-0:58-214-a7b59a6452dec7875146a2a116537b34939740222be11bcbfea5e439c2bb9b2e 253:4    0  300M  0 dm
  ├─container-0:58-214-ecd6a44cfcb073271a605b28dab3eaf2467dce9f9bdf1f432e4fc577fa050a3f 253:23   0  300M  0 dm
  ├─container-0:58-214-a8e8ad2a31a552da9da274b2ee49f956a6918eed49534cf6c9d31a4db33ad218 253:13   0  300M  0 dm
  ├─container-0:58-214-9270e22487cc39faf1cbc3abf75f3074e91aaf545d22c59e5131b664ba8d7395 253:2    0  300M  0 dm
  ├─container-0:58-214-033f3541104a57efc52e81465e0d09044b2b207f7d1b97f9b8284183aece27fb 253:11   0  300M  0 dm
  ├─container-0:58-214-d45e9c752a0568fd7b2466a6561993816da5fb856eafc7c3f9701b99e3f7f291 253:9    0  300M  0 dm
  ├─container-0:58-214-360e2aec1431b2014c4881aebb946180f87e458a210fc4662f9366638b7263bf 253:28   0  300M  0 dm
  ├─container-0:58-214-ea00d067934b45645ea4dfa432b5114809fbf0b346497de2c5b869ff18ed4127 253:18   0  300M  0 dm
  ├─container-0:58-214-4812ce92662814c34c378df3f92b7607c8922b7614807883117bb13d38fc0eeb 253:7    0  300M  0 dm
  ├─container-0:58-214-abe135da71aec96d1553fe7e6ad598e8f9eefd9a5de8ecfc834f04615beb6a9d 253:26   0  300M  0 dm
  ├─container-0:58-214-7fecee9c62f05b300a765be27bdaed7466b544286f38a7d25630d37406ada419 253:16   0  300M  0 dm
  ├─container-0:58-214-bc7ded9e60a19b89fe34f1cf2c4da36757c9e0ca265ef10e4a2a5aa896bd1568 253:5    0  300M  0 dm
  ├─container-0:58-214-955104feaf86370bdd924d5a543dd3a8c417301018631896e1a36114dd44b85a 253:24   0  300M  0 dm
  ├─container-0:58-214-4f4b854955c5fa094c2b720b9cf48e3dbcc6626d8a93fc9ed60b5d712957a814 253:14   0  300M  0 dm
  ├─container-0:58-214-ac37c6f0174afdd813592227cecd33bd905fa0152307c441385d719a23bedb60 253:3    0  300M  0 dm
  ├─container-0:58-214-30f0d1ed75b809d65ed616d89f9b6bb9fe8c72e9e9ac7be4cad6f30ab7c85882 253:22   0  300M  0 dm
  └─container-0:58-214-9328cb707ef2b1bab9167d77964c2f8385f4c38b1eac0c7d71a735048b9dec81 253:12   0  300M  0 dm
sda                                                                                       8:0    0   30G  0 disk
└─sda1                                                                                    8:1    0   30G  0 part /

fuentess@kata-xenial:~/go/src/github.com/containers/storage$ sudo lvs
fuentess@kata-xenial:~/go/src/github.com/containers/storage$ sudo vgs
fuentess@kata-xenial:~/go/src/github.com/containers/storage$ sudo pvs

```

I was sure there was no physical volume on /dev/sdb, so not sure why the test says that it cannot use the device.

**Comment by runcom** [comment]
e2e are still broken in master, hold on for #1772

**Comment by umohnani8** [comment]
@rhatdan is this still needed? I recently vendored in containers/image and containers/storage with the lock fixes. Can you please rebase if it is still needed.

**Pull request closed without merging**
