### PR TITLE
lib/container_server: Split locale at the first dot, etc.

### PR DESCRIPTION
**Pull request by wking**
This ports containers/libpod@69cb8639 (containers/libpod#2550) to CRI-O.

### CODE REVIEW

**Comment by mrunalp** [comment]
@vrothberg ptal

**Comment by giuseppe** [comment]
LGTM

**Comment by vrothberg** [comment]
LGTM although I would prefer libpod to expose that as a public API to avoid copying code.

**Comment by wking** [comment]
> LGTM although I would prefer libpod to expose that as a public API to avoid copying code.

Sounds good to me, although isn't the plan to consume higher-level libpod APIs?  I haven't been tracking the progress of that unification.

**Comment by vrothberg** [comment]
> > LGTM although I would prefer libpod to expose that as a public API to avoid copying code.
> 
> Sounds good to me, although isn't the plan to consume higher-level libpod APIs? I haven't been tracking the progress of that unification.

That's correct. I hope we can start the migration soon :)

**Pull request merged**
