### PR TITLE
[1.12] Use fsync instead of sync for stateful set tests

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom PTAL
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
Mmm it's failing here, also, do we need a PR upstream as well? 
/test e2e_rhel

**Comment by mrunalp** [comment]
@runcom There might be some other issue lurking as well. Next time it hangs, we need to go in and check.

**Pull request merged**
