### PR TITLE
[1.10] test: Switch to golang 1.11.6

### PR DESCRIPTION
**Pull request by mrunalp**
Some of the packages that we rely on don't compile with 1.9 anymore.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@chavafg @sboeuf Can you check if kata failures here are 1.10 specific?

**Comment by sboeuf** [comment]
Some flaky tests with `exec`... We're currently investigating.

**Comment by chavafg** [comment]
still failing. Taking a further look, it fails stopping the pod:
```
15:00:19 # time="2019-03-20 20:59:57.319690885Z" level=debug msg="StopPodSandboxRequest &StopPodSandboxRequest{PodSandboxId:e7f0e0e241dfbf37f3abc5c4b393fc4a548e993af5111db0e2ebb6a4307c40f8,}" 
15:00:19 # time="2019-03-20 20:59:57.476270728Z" level=debug msg="event: "/var/run/crio/exits/3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8.8LI3YZ": RENAME" 
15:00:19 # time="2019-03-20 20:59:57.476311428Z" level=debug msg="event: "/var/run/crio/exits/3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8": CREATE" 
15:00:19 # time="2019-03-20 20:59:57.476322628Z" level=debug msg="container or sandbox exited: 3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8" 
15:00:19 # time="2019-03-20 20:59:57.476351228Z" level=debug msg="container exited and found: 3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8" 
15:00:19 # rpc error: code = Unknown desc = Failed to remove paths: map[devices:/sys/fs/cgroup/devices/Burstable/pod_123-456/crio-3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8 net_prio:/sys/fs/cgroup/net_cls,net_prio/Burstable/pod_123-456/crio-3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8 freezer:/sys/fs/cgroup/freezer/Burstable/pod_123-456/crio-3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8 name=systemd:/sys/fs/cgroup/systemd/Burstable/pod_123-456/crio-3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8 pids:/sys/fs/cgroup/pids/Burstable/pod_123-456/crio-3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8 blkio:/sys/fs/cgroup/blkio/Burstable/pod_123-456/crio-3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8 net_cls:/sys/fs/cgroup/net_cls,net_prio/Burstable/pod_123-456/crio-3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8 perf_event:/sys/fs/cgroup/perf_event/Burstable/pod_123-456/crio-3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8 cpuset:/sys/fs/cgroup/cpuset/Burstable/pod_123-456/crio-3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8 memory:/sys/fs/cgroup/memory/Burstable/pod_123-456/crio-3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8 cpu:/sys/fs/cgroup/cpu,cpuacct/Burstable/pod_123-456/crio-3f96d3dfd1685fc0413d3134e022df00ebbc5e054d5b54e760a6f4e5efa4baf8 cpuacct:/sy
```

not sure if there was a fix for this after 1.10

**Pull request merged**
