### PR TITLE
[release-1.11] container_create: fix dev mounts and remove nodev from /dev mounts

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

same as #1884 but for 1.11

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by mrunalp** [comment]
:+1:

**Comment by runcom** [comment]
@rhatdan PTAL and lgtm to merge

**Pull request merged**
