### PR TITLE
Add disk usage for ListContainerStats

### LINKED ISSUE #1800: CRI-O does not report disk statistics via `ListContainerStats` CRI call
**Description**

`CRI-O` does not report disk usage statistic via the `ListContainerStats` rpc call.

In the container stat struct `writable_layer` is currently set to `nil` which cause to report `0` for `used_bytes` and `inodes_used`
https://github.com/kubernetes-sigs/cri-o/blob/4cd5a7c60349be0678d9f1b0657683324c1a2726/server/container_stats.go#L29

**Steps to reproduce the issue:**
You can observe the issue using `crictl -r unix:///var/run/crio/crio.sock stats` that is using `ListContainerStats` and will report zeroes for disk statistics:

**Describe the results you received:**
```
CONTAINER           CPU %               MEM                 DISK                INODES
226d6c4186105       4.81                126.3MB             0B                  0
4b4f4d525501c       0.20                33.66MB             0B                  0
5cb52ff953c2a       1.41                25.79MB             0B                  0
```

**Describe the results you expected:**
Using `containerd` will display disk usage statistics:
```
CONTAINER           CPU %               MEM                 DISK                INODES
28103c8d7ea02       1.51                28.56MB             32.77kB             9
95591751cd28c       3.88                39.46MB             36.86kB             9
a322d22343340       1.66                26MB                20.48kB             5
```

**Output of `crio --version`:**

```
crio version 1.11.3-dev
```

### PR DESCRIPTION
**Pull request by QiWang19**
Signed-off-by: Qi Wang <qiwan@redhat.com>

Pick required changes from #1869 and fix #1800 
@lsm5 PTAL and thanks

### CODE REVIEW

**Comment by mrunalp** [comment]
@QiWang19 Can we add a test for this as a follow-on PR?

**Comment by QiWang19** [comment]
> @QiWang19 Can we add a test for this as a follow-on PR?

ok :ok_hand: will add tests for this later

**Pull request merged**
