### PR TITLE
Vendor in latest c/storage and c/image

### PR DESCRIPTION
**Pull request by mtrmac**
<s>WIP, do not merge: Right now only <s>to have a fallback implementation and</s> to get it through CI.</s>

<s>**The c/image branch is unmerged upstream.**</s>

If this is a bug fix, make sure your description includes "fixes #xxxx", or
"closes #xxxx"

**- What I did**

Tried to fix `Manifest does not match provided manifest` failures.

**- How I did it**

Updated c/storage to support storing multiple manifests for a single `Image` object (which are deduplicated per config), and c/image to a WIP branch to take advantage of it by using the user-requested manifest instead of always the latest recorded.

**- How to verify it**

For now, only the existing tests.

**- Description for the changelog**
TBD

### CODE REVIEW

**Comment by mrunalp** [comment]
Can we open this against `release-1.12` branch? That's where we need to land the fixes first. The e2e tests seem to be failing on some regression upstream.

**Comment by mtrmac** [comment]
> Can we open this against `release-1.12` branch? That's where we need to land the fixes first.

See #2066.

**Comment by mrunalp** [comment]
Rebase to master should fix the tests.

**Comment by mtrmac** [comment]
Rebased, tests pass.

**Pull request merged**
