### PR TITLE
[releaese-1.12] bump to v1.12.0

### PR DESCRIPTION
**Pull request by runcom**
This PR bump to v1.12.0. Due to the changes in the runtime handlers, we will tag https://github.com/kubernetes-sigs/cri-o/commit/a03998c15a884de8077e6312ccd8fde730b132c9 as `v1.12.0` but we'll need a changelog for migrating the config.

@mrunalp @rhatdan @sboeuf PTAL

### CODE REVIEW

**Comment by runcom** [comment]
all green here

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
