### PR TITLE
[1.10] fix some race conditions with short lived pods

### PR DESCRIPTION
**Pull request by giuseppe**
Backport of #1957

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
I have opened #2151 to fix the CI issues.

**Comment by mrunalp** [comment]
Can you rebase on top of #2151? It should fix the tests.

**Comment by mrunalp** [comment]
If you rebase over #2166 travis should pass now.

**Comment by giuseppe** [comment]
@mrunalp only kata is failing now

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
