### PR TITLE
[release-1.12] container_create: fix dev mounts and remove nodev from /dev mounts

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

same as #1884 but for 1.12

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
@rhatdan PTAL and lgtm to merge

**Comment by rhatdan** [comment]
LGTM, is Kata broken?

**Comment by runcom** [comment]
> LGTM, is Kata broken?

yes, that's known

**Comment by rhatdan** [comment]
@runcom I am not allowed to run `/lgtm`,  I am not sure of the state for me being added to kubnernetes-sig

**Comment by runcom** [comment]
@mrunalp this and the other 1.11 PR should be ready to be merged so we can cut new releases

**Comment by mrunalp** [comment]
@rhatdan You should have received an invite to kubernetes-sigs like Giuseppe did.

**Pull request merged**
