### PR TITLE
Add oci unit tests

### PR DESCRIPTION
**Pull request by saschagrunert**
This PR contains the unit tests of the `oci` package. The coverage is pretty low for now, because there is no lower level abstraction (like for system calls).

### CODE REVIEW

**Comment by saschagrunert** [comment]
Please take a look here too. I was a little bit reluctant in adding further abstractions just for testing, that is why the coverage seems a bit low to me. Also taking the RuntimeV2 (#2024) implementation into account, I'm wondering how we want to continue here. Possible options:

- Leave the unit  test coverage low and test the OS related stuff only via integration tests
- Add an OS abstraction layer which is mock-able

WDYT?

**Comment by saschagrunert** [comment]
I rebased on top of the latest master branch and resolved the conflict.

**Comment by umohnani8** [comment]
Changes LGTM

**Pull request merged**
