### PR TITLE
Move container implementations from lib to oci package

### LINKED ISSUE #1946: Move container implementations from lib to oci package
We need to make sure nothing specific to `conmon` is being done from the lib package. Only `oci.Runtime` should be allowed to deal with details of how `conmon` interacts with the container runtime, which will allow for a better abstraction.

### PR DESCRIPTION
**Pull request by sboeuf**
A lot of assumptions regarding `conmon`, but also the fact that containers
run on the host, hence they have a valid PID, are made everywhere in the
codebase.

Because we want to better support VM based container runtimes, it is
necessary to make sure we don't make such assumptions from high layers
such as `lib` package. Instead, those implementation details should be
handled by the oci.Runtime directly.

Fixes #1946

### CODE REVIEW

**Comment by sboeuf** [comment]
@mrunalp @runcom PTAL

**Comment by mrunalp** [comment]
I am going to run some things manually before merging this.

**Comment by sboeuf** [comment]
Makes sense, thanks @mrunalp

**Comment by sboeuf** [comment]
@mrunalp no rebase needed :)

**Comment by mrunalp** [comment]
This looks fine to me. @runcom ptal.

**Comment by mrunalp** [comment]
Also @giuseppe :)

**Comment by giuseppe** [comment]
LGTM

**Pull request merged**
