### PR TITLE
test: Fixup kubernetes-incubator to kubernetes-sigs

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom PTAL
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
We need fix from aos-cd-jobs for the ami jobs

**Comment by runcom** [comment]
jobs have not been updated yet.

**Comment by mrunalp** [comment]
@runcom Merge this if this is all green (hopefully) :)

**Comment by wking** [comment]
Did you intentionally skip [this][1] (and the other kubernetes-incubator/cri-o reference further down in that file)?

[1]: https://github.com/kubernetes-sigs/cri-o/blob/7402a30ecf2a79b0798acd3179d1ec0e484d56fd/Vagrantfile#L40

**Pull request merged**
