### PR TITLE
Add goimports, staticcheck, prealloc linters

### PR DESCRIPTION
**Pull request by saschagrunert**
Hey, with this PR the following linters will be enabled and the corresponding issues are fixed:

* goimports: https://github.com/golang/tools/tree/master/cmd/goimports
* staticcheck: https://github.com/dominikh/go-tools/tree/master/staticcheck
* prealloc: https://github.com/alexkohler/prealloc

### CODE REVIEW

**Comment by rhatdan** [comment]
/ok-to-test
LGTM
/test all

**Comment by rhatdan** [comment]
@saschagrunert Love to get you contributing some of this stuff into libpod, since we plan on merging that into CRI-O at some point.

**Comment by saschagrunert** [comment]
> @saschagrunert Love to get you contributing some of this stuff into libpod, since we plan on merging that into CRI-O at some point.

Oh yeah sure, sounds good!

**Comment by mrunalp** [comment]
I opened #2156 for e2e build failures.

**Comment by mrunalp** [comment]
Rebasing to master should fix the tests. Thanks!

**Pull request merged**
