### PR TITLE
[1.13] fix some race conditions with short lived pods

### PR DESCRIPTION
**Pull request by mrunalp**
Backport of #1957

### CODE REVIEW

**Comment by mrunalp** [comment]
@giuseppe ptal. Also, we need to open backports for 1.9 - 1.12. Can you open a few? :) I will get the rest tomorrow.

**Comment by giuseppe** [comment]
LGTM

**Comment by giuseppe** [comment]
> @giuseppe ptal. Also, we need to open backports for 1.9 - 1.12. Can you open a few? :) I will get the rest tomorrow.

Sure!  Opened:

1.9 - https://github.com/kubernetes-sigs/cri-o/pull/2145
1.10 - https://github.com/kubernetes-sigs/cri-o/pull/2146
1.11 - https://github.com/kubernetes-sigs/cri-o/pull/2147
1.12 - https://github.com/kubernetes-sigs/cri-o/pull/2148

**Pull request merged**
