### PR TITLE
BACKPORT: Add nodev to options of bind mounts from kube

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@linux.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
Need to rebase this maybe

**Comment by runcom** [comment]
rebased
/test all

**Comment by mrunalp** [comment]
I just updated release-1.11 with the test fix.

**Pull request merged**
