### PR TITLE
Add runtime handlers support

### PR DESCRIPTION
**Pull request by runcom**
This is the same as #1822 but rebased onto master to run the tests while waiting on a rebase there

### CODE REVIEW

**Comment by runcom** [comment]
everything's cool here :)

**Comment by runcom** [comment]
2 green in a row, let's see again
/test all

**Comment by runcom** [comment]
flake
/test critest_rhel

**Comment by runcom** [comment]
This is good to go assuming we're using this in favor of https://github.com/kubernetes-sigs/cri-o/pull/1822

@sboeuf @mrunalp PTAL

**Comment by runcom** [comment]
@mrunalp @sboeuf PTAL

**Comment by sboeuf** [comment]
:+1:
@runcom @mrunalp Please let me know when you cut 1.12 :smile:

**Pull request merged**
