### PR TITLE
[WIP] Enabling some k8s tests

### PR DESCRIPTION
**Pull request by umohnani8**
Just checking if we are still seeing the test failures.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
Following up on https://github.com/kubernetes-sigs/cri-o/issues/1529, the tests failures are down to 5 but it is the same timeout issue as we were seeing before.
the timeout is happening on `/bin/sh -x -c wget -qO- http://127.0.0.1:31512/`.
@mrunalp any idea who I can ping on this?

**Comment by mrunalp** [comment]
We can ping the networking/SDN team.

**Comment by dcbw** [comment]
The NodeInternalIP of the node in e2e_rhel is 127.0.0.1. That is incorrect, and is causing testcases like "should be able to switch session affinity for NodePort service" to try requesting the nodeport service on 127.0.0.1. See:

```
It] should be able to switch session affinity for NodePort service
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1678
[1mSTEP[0m: creating service in namespace services-592
[1mSTEP[0m: creating service service in namespace services-592
[1mSTEP[0m: creating replication controller service in namespace services-592
I0315 19:26:20.125366   31051 runners.go:184] Created replication controller with name: service, namespace: services-592, replica count: 3
I0315 19:26:23.175755   31051 runners.go:184] service Pods: 3 out of 3 created, 3 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Mar 15 19:26:23.181: INFO: Creating new exec pod
Mar 15 19:26:25.201: INFO: Running '/go/src/k8s.io/kubernetes/_output/bin/kubectl --server=https://172.18.29.38:6443 --kubeconfig=/var/run/kubernetes/admin.kubeconfig exec --namespace=services-592 execpod-affinityplj7q -- /bin/sh -x -c wget -qO- http://127.0.0.1:31469/ -T 2'
Mar 15 19:26:25.390: INFO: rc: 1
Mar 15 19:26:25.390: INFO: Failed to get response from 127.0.0.1:31469. Retry until timeout
Mar 15 19:26:27.390: INFO: Running '/go/src/k8s.io/kubernetes/_output/bin/kubectl --server=https://172.18.29.38:6443 --kubeconfig=/var/run/kubernetes/admin.kubeconfig exec --namespace=services-592 execpod-affinityplj7q -- /bin/sh -x -c wget -qO- http://127.0.0.1:31469/ -T 2'
```

Note the wget request for 127.0.0.1:31469. 'kubectl exec' runs tests inside the given container, in this case services-592/execpod-affinityplj7q. That container is *not* a hostNetwork container, according to the tests:

```
	It("should be able to switch session affinity for NodePort service", func() {
		svc := getServeHostnameService("service")
		svc.Spec.Type = v1.ServiceTypeNodePort
		execAffinityTestForNonLBService(f, cs, svc, true)
	})

...

func execAffinityTestForNonLBService(f *framework.Framework, cs clientset.Interface, svc *v1.Service, isTransitionTest bool) {
...
	execPodName := framework.CreateExecPodOrFail(cs, ns, "execpod-affinity", nil)

...

func CreateExecPodOrFail(client clientset.Interface, ns, generateName string, tweak func(*v1.Pod)) string {
	Logf("Creating new exec pod")
	execPod := newExecPodSpec(ns, generateName)
	if tweak != nil {

...

// newExecPodSpec returns the pod spec of exec pod
func newExecPodSpec(ns, generateName string) *v1.Pod {
	immediate := int64(0)
	pod := &v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			GenerateName: generateName,
			Namespace:    ns,
		},
		Spec: v1.PodSpec{
			TerminationGracePeriodSeconds: &immediate,
			Containers: []v1.Container{
				{
					Name:    "exec",
					Image:   BusyBoxImage,
					Command: []string{"sh", "-c", "trap exit TERM; while true; do sleep 5; done"},
				},
			},
		},
	}
	return pod

```

The execpod is *not* hostNetwork:true, so trying to request 127.0.0.1 inside the execpod isn't going to do anything because the NodePort service isn't running inside the execpod.

The core problem looks to be that the kubelet service is posting the wrong NodeInternalIP to the apiserver; it cannot ever post 127.0.0.1. And indeed, looking at kubelet logs:

```
I0315 18:53:18.147616   25682 flags.go:33] FLAG: --address="127.0.0.1"
I0315 18:53:18.148301   25682 flags.go:33] FLAG: --hostname-override="127.0.0.1"
```

I don't know what's configuring kubelet in this e2e setup, but whatever it is, it's doing it wrong :)

**Pull request closed without merging**
