### PR TITLE
Add support for writing stacks with SIGUSR1

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom @umohnani8 @rhatdan PTAL

### CODE REVIEW

**Comment by runcom** [comment]
Kata still complaining but this LGTM

**Comment by mrunalp** [comment]
@runcom Updated.

**Comment by sboeuf** [comment]
@runcom @mrunalp sorry with the inconsistent Kata CI here... We have some problems with the type of VM being assigned to our CI, meaning that sometimes they don't have the expected nested support, and we simply cannot run Kata on them.

**Comment by mrunalp** [comment]
@sboeuf okay, thanks for the info!

**Pull request merged**
