### PR TITLE
[release-1.11] server: serve streaming on localhost on a random port

### PR DESCRIPTION
**Pull request by runcom**
same as https://github.com/kubernetes-incubator/cri-o/pull/1714 but for `release-1.11`

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
Can we manually test and make sure that cross host oc exec/attach work fine with this? The e2e won't test it.

**Comment by rhatdan** [comment]
@runcom did you manually test this so we can merge it?

**Comment by umohnani8** [comment]
LGTM
@mrunalp tests are green.

**Pull request merged**
