### PR TITLE
[release-1.11] test: Run e2e in parallel

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom Let's see a few runs on 1.11

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
Passed once. Trying again.

**Comment by runcom** [comment]
this looks good, re-trigger e2e
/test all

**Comment by mrunalp** [comment]
All runs have passed so far. One more to be certain.

**Pull request merged**
